name: CI
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches:
      - master
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [
          { name: Arm Ubuntu, label: ubuntu-latest-arm },
          { name: X86 Ubuntu, label: ubuntu-latest },
          { name: X86 Windows, label: windows-latest },          
        ]

      name: CI-${{ matrix.os.name }}
      runs-on: ${{ matrix.os.label }}
      steps:
      - name: Checkout EqTools
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
      - name: Install EqTools
        run: python -m pip install .